version: '3.8'

services:
  backend:
    build: ./backend
    container_name: doc-assistant-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=logic.py
      - FLASK_ENV=development

  frontend:
    build: .
    container_name: doc-assistant-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend